#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - feature/appveyor

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: AnyCPU
configuration: Release

build:
  project: WeavR.sln

before_build:
  - nuget restore
  - nuget restore -source "https://www.myget.org/F/distantcam"

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: output\*.nupkg