#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - feature/appveyor

#---------------------------------#
#    environment configuration    #
#---------------------------------#

install:
  # Fix repo so gitversion works
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch -q
  - git checkout -qf feature/appveyor

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: AnyCPU
configuration: Release

build:
  project: WeavR.sln

before_build:
  - nuget restore

after_build:
  - nuget push output\*.nupkg 7b6f94fd-d004-4888-a8e4-838073330029 -Source https://www.myget.org/F/weavr/api/v2/package

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: output\*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

#deploy:
#  provider: NuGet
#  server: https://www.myget.org/F/weavr/api/v2/
#  api_key:
#    secure: vojumGDCfpdh8Vtd/yaww0I+ROJcjS0FdVHAcSNjzWgb+lATZEKjPr/uduXysxIf
#  artifact: output\*.nupkg