#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: AnyCPU
configuration: Release

build:
  project: WeavR.sln

before_build:
  - nuget restore -source "https://www.nuget.org/api/v2;https://www.myget.org/F/distantcam"

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: output\*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  provider: NuGet
  server: https://www.myget.org/F/weavr/api/v2/package
  api_key:
    secure: ZsjvLL66BTiQ9u/kEOL40ElyopeSEWPynBjLCoiFWVvFF5qS+KnYMaSQcuLsaYgv
  on:
    branch: develop